version: '3.4'

networks:
  customerapi:

services:
  webapi:
    container_name: customer_api
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .  
      dockerfile: src/v1/Web.Api/Dockerfile
    ports:
      - 8080:8080
      - 8001:80
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=CUSTOMER
      - DB_SA_PASSWORD=password@12345#
      - ASPNETCORE_ENVIRONMENT=Development
    networks: 
      - customerapi
  db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks: 
      - customerapi
  collector:
    container_name: otel_collector
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - 8888:8888
      - 8889:8889
      - 13133:13133
      - 4317
      - 4318
    depends_on:
      - jaeger
    networks: 
      - customerapi
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 9411:9411
    networks: 
      - customerapi