version: '3.4'

networks:
  customerapi:

services:
  webapi:
    container_name: customer_api
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .  
      dockerfile: src/v1/Web.Api/Dockerfile
    ports:
      - 8080:8080
      - 8001:80
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=Customer
      - DB_SA_PASSWORD=password@12345#
      - ASPNETCORE_ENVIRONMENT=Development
    networks: 
      - customerapi
  db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks: 
      - customerapi