receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp/tracing:
    endpoint: jaeger:4317
    tls:
      insecure: true
  # otlp/metrics:
  #   endpoint: "prometheus:9090"
  # otlp/logs:
  #   endpoint: "loki:4318"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tracing]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp/metrics]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp/logs]