name: Continuos Integration .NET

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The Environment to deploy to'
        required: true
        type: choice
        default: 'development'
        options:
          - development
          - stage 
          - production

  pull_request:
    types:
      - opened
    branches:
      - main
      - 'release/**'
    paths:
      - '**.cs'
      - '.github/workflows/**'

  push:
    branches:
      - main
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
    paths:
      - '**.cs'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Web.Api.sln
      - name: Build
        run: dotnet build Web.Api.sln

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Unit Tests
        run: dotnet test ./tests/UnitTests/UnitTests.csproj
        