name: Continuos Integration .NET

on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'release/**'
    paths:
      - '**.cs'
      - '.github/workflows/**'
  push:
    branches:
      - main
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
    paths:
      - '**.cs'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Print working directory
        run: pwd
      - name: Restore dependencies
        run: dotnet restore Web.Api.sln
      - name: Build
        run: dotnet build Web.Api.sln

  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set working directory
        run: cd workspace/projects/Customer-API
      - name: Unit Tests
        run: dotnet test ./tests/UnitTests/UnitTests.csproj
        