name: Continuos Integration .NET

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The Environment to deploy to'
        required: true
        type: choice
        default: 'development'
        options:
          - development
          - stage 
          - production

  pull_request:
    types:
      - opened
    branches:
      - main
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
    paths:
      - '**.cs'
      - '.github/workflows/**'

  push:
    branches:
      - main
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
    paths:
      - '**.cs'
      - '.github/workflows/**'

  issues:
    types:
      - opened
      - edited
    branches:
      - main
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**' 
    paths:
      - '**.cs'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore Web.Api.sln
      - name: Build
        run: dotnet build Web.Api.sln

  # fortify:
  #   name: Fortify
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  # sonarqube:
  #   name: Sonarqube
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    # needs: [fortify, sonarqube]
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Unit Tests
        run: dotnet test ./tests/UnitTests/UnitTests.csproj

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    # needs: [fortify, sonarqube]
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Integration Tests
        run: dotnet test ./tests/IntegrationTests/IntegrationTests.csproj